name: Build and Test

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.cs'
      - '**/*.csproj'

env:
  DOTNET_VERSION: 8.0

jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      - name: Install Dependencies
        run: dotnet restore
        working-directory: Weather-Application

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: Weather-Application

      - name: Test
        run: dotnet test --no-restore --verbosity normal
        working-directory: WeatherSystem.Tests
